// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_med67rb-PlB9U-goUYR1ZlkK88kYaVA',
    appId: '1:704741265554:web:122cc6b4045f070631164b',
    messagingSenderId: '704741265554',
    projectId: 'schedule-data-e6166',
    authDomain: 'schedule-data-e6166.firebaseapp.com',
    databaseURL: 'https://schedule-data-e6166-default-rtdb.firebaseio.com',
    storageBucket: 'schedule-data-e6166.firebasestorage.app',
    measurementId: 'G-KX846174YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRnvpxqUf6d9Pg6Al-oUJ_g3T46R7v-CI',
    appId: '1:704741265554:android:5958bf2513f85e6331164b',
    messagingSenderId: '704741265554',
    projectId: 'schedule-data-e6166',
    databaseURL: 'https://schedule-data-e6166-default-rtdb.firebaseio.com',
    storageBucket: 'schedule-data-e6166.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_med67rb-PlB9U-goUYR1ZlkK88kYaVA',
    appId: '1:704741265554:web:7e6fc0e55414995731164b',
    messagingSenderId: '704741265554',
    projectId: 'schedule-data-e6166',
    authDomain: 'schedule-data-e6166.firebaseapp.com',
    databaseURL: 'https://schedule-data-e6166-default-rtdb.firebaseio.com',
    storageBucket: 'schedule-data-e6166.firebasestorage.app',
    measurementId: 'G-DS8XGTE617',
  );

}